/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        

        import  {useRef}  from 'react'
        import { useGLTF
        
         } from '@react-three/drei'

        

 export const  Audifonos= (props:any)=> {
  const group = useRef()
          const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/headphones/model.gltf') as any
          return (
            <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Cushion.geometry} material={materials.Cushion} />
            <mesh geometry={nodes.Ear_Cup.geometry} material={nodes.Ear_Cup.material} />
            <mesh geometry={nodes['Mid-'].geometry} material={materials['Black-2']} />
            <mesh geometry={nodes.Seprator001.geometry} material={nodes.Seprator001.material} />
            <mesh geometry={nodes.Seprator.geometry} material={materials.Connector} />
            <mesh geometry={nodes.Cylinder025.geometry} material={nodes.Cylinder025.material} />
            <mesh geometry={nodes.Cylinder025_1.geometry} material={materials.GlowBlue} />
            </group>
          )
        }

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/headphones/model.gltf')