/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export const Chair = (props: any) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/bench-2/model.gltf') as any
  materials.body_orange = new THREE.MeshStandardMaterial({ color: '#cc7e47', envMapIntensity: 1, metalness: 0, roughness: 0.3 })
  return (
    <group  ref={group}  {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench.geometry}
        material={materials['BrownDark.042']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/bench-2/model.gltf')