/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
      
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export const Doge = (props: any) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/dogue/model.gltf') as any
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh001.geometry} material={materials.eyes} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh001_1.geometry} material={materials.eyes_pupile} />
      <mesh castShadow receiveShadow geometry={nodes.nose.geometry} material={materials.nose} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh002.geometry} material={materials['body_orange-light']} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh002_1.geometry} material={materials.body_orange} />
    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/dogue/model.gltf')